server:
  port: 8080
  undertow:
    buffer-size: 1024
    direct-buffers: true
  servlet:
    context-path: /trans

logging:
  config: classpath:log4j2.xml
  level:
    root: INFO

mapper:
  before: false
  check-example-entity-class: true
  enable-method-annotation: true
  enum-as-simple-type: true
  identity: mysql
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true
  safe-delete: true
  safe-update: true
  use-java-type: true
mybatis:
  check-config-location: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.trans.payment.core.entity
pagehelper:
  helperDialect: mysql
  offset-as-page-num: false
  page-size-zero: false
  params: count=countSql
  reasonable: false
  row-bounds-with-count: false
  supportMethodsArguments: true

spring:
  mvc:
      throw-exception-if-no-handler-found: true #出现 404 错误时, 直接抛出异常
  application:
    name: trans-core
  redis:
    host: 39.97.101.65
    port: 6379
    password: privateTest
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.97.101.65:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      username: root
      password: privateTest