package com.open.demo.utils;

import javax.print.DocFlavor.STRING;

public class Constant {
  public final static String GATEWAY_URL = "http://127.0.0.1:8090/gateway";
  public final static String ORGANIZATION_ID = "test";
  public final static String SIGN_TYPE = "RSA";
  public final static String VERSION = "1.0";
  public final static String PUBLIC_KEY = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCx3etyM1TxVSX9cmmVU8eIhcXHhtxVwLNkpFCn1VgERXoYOPRiHrlZcTv4WfZXVGjykpeHibrKpLe+nKYfNxhaGF8Z+wkvGKiRVVv1HlqAHxmGlpMtRRgSLf6rpxFqv1hN3eJoG9UA9BuxBQiHQVYb82R7hE7GNjhJeAX0IUCS7QIDAQAB";
  public final static String PRIVATE_KEY = "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBANMBfZ7BSkx5BdE1ef4ZgHGCRWA9cqul9T+ICt6bHq68WSgNPnoPf9onflsJbeDh0eOo7HSLFlqowxGe3MQzy7vncTNxWuv3Y8lisUdF5nABAUCmeAyzRgr7YN1Jw8/GGe5vxyuMiEJXd8rCGKisd9RQhtzAPGFN1VIz7NkmfNr3AgMBAAECgYEAyuLJDefe7+8CF+oqdZfBt+LBoEsVQlRdnwvJH8fZVbxGocsyQp06muGUjiZf33ZioVtgmKLQCLXycrPkpEcFYdWoH9cHit7hjvJIMVSu5Zvqru4Vdghzs5YkC1e6UtCqu9z2tfcu1SHFREUkjUWQmqsddKXHnp5y6bBsHuuQGVECQQDrZVkzUJGS4NkbzgfCp6jdIzoU7yfZQgtyGMxNjUO24a7RyWOSA98+kYLtnEVY6I6nyUHPAoKKkplUUiENHhRpAkEA5XmesoHluSsvR3jdROaaidTXRgXjpTlkTLkTYQOIIpVjSpoDk4VQ7mdmTzpI87eSR41ng4p1/nc4u2Aj5DAIXwJASFE8lD0+W+dkC9zCGZU0lauK3n+SuHZH2eewbGrn0LmI4b6DLoqt/STrGmCWFXhsyzNTWmuk+zmKjZMlwEfrcQJASTHJ1NZqF+4WXo3Gxjtn/57MK6GlQwZTX8WI0OD3g1BzI1CM43kan3CLyamlq1daaUhJREPd7xTIG7xGtno7sQJBANUaTuvxHioV4eizrwUC5fr401w30TfSLPbx4D6yY26na6KvWVIXnw6YRltOXjjqVHpjwBzgB1yv7RZ/nvxQbSg=";

}
